// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d780ab45-67d7-4077-9e1a-44acbe5a0bd9",
    "aws_cognito_region": "us-west-2",
    "aws_mobile_analytics_app_id": "bb7806c3280748d6bf3704eaa2c1c55c",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
